# Generated by Django 3.2.6 on 2021-09-03 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50, unique=True)),
                ('pull_factor', models.IntegerField(default=85)),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competitor_no', models.IntegerField(unique=True)),
                ('competitor_name', models.CharField(max_length=50)),
                ('tractor_name', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('pull_factor', models.IntegerField(default=85)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitors.class')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.FloatField()),
                ('run_date', models.DateField(verbose_name='date run')),
                ('run_time', models.TimeField(verbose_name='time run')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitors.competitor')),
            ],
        ),
        migrations.AddField(
            model_name='competitor',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitors.event'),
        ),
    ]
