# Generated by Django 3.2.6 on 2021-09-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='pull_factor',
            field=models.IntegerField(default=85),
        ),
        migrations.AddField(
            model_name='result',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
