# Generated by Django 3.2.6 on 2021-09-05 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0002_auto_20210903_0844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitor',
            old_name='_class',
            new_name='clasS',
        ),
    ]
