# Generated by Django 3.2.6 on 2021-09-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0003_rename__class_competitor_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='tractor_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
