# Generated by Django 3.2.6 on 2021-09-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0005_result_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='result',
            name='event_name',
            field=models.CharField(max_length=50),
        ),
    ]
