# Generated by Django 3.2.6 on 2021-09-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitors', '0006_auto_20210910_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='competitor_no',
            field=models.IntegerField(),
        ),
    ]
